---
title: "Results from Simulation 1 of the Constrained Reference Region Model"
runtime: shiny
---

# Quick info

- 10,000 replications at Concentration-Noise-Ratio from 5:5:50
- TemporalResolutions: 1s, 5s, 10s, 15s, 30s, 60s
- Using the literature-based/population-averaged AIF from Parker et al.
- Reference region kinetics:
    + KTrans_RR = 0.1 /min
    + ve,RR = 0.1
    + kep,RR = 1.0 /min
- Tumour kinetics:
    + KTrans = 0.25 /min
    + ve = 0.4
    + kep = 0.625 /min

- Note: Error bars are not plotted for ve because LRRM often has extremely large error bars, which washes away the relatively smaller differences between the mean percent errors.

Description of model names:  
- LRRM: Linear Reference Region Model  
- CLRRM: Constrained Linear Reference Region Model, with kepRR estimated using median (manuscript version)  
- CLRRMm: CLRRM with kepRR estimated using the mean (or interquartile mean?) - best to ignore this one  
- CLRRMt: CLRRM with the true kepRR value used - i.e. instead of estimated kepRR, we used the true simulated value  
- NRRM: Non-linear Reference Region Model  
- CNRRM: Constrained Non-linear Reference Region Model  
- CHRRM: Constrained Hybrid Reference Region Model  

```{r, echo=FALSE, warning=FALSE}
## Required libraries from CRAN
library(shiny)
library(ggplot2)
library(Cairo)
library(knitr)
options(shiny.usecairo=T)

csvFile = "../dataResults/e01-simResults-refY.csv"

## Load data
csvData <- read.csv(csvFile)
CNRChoices <- unique(csvData$CNR)
TResChoices <- unique(csvData$TemporalRes)
modelChoices <- levels(csvData$FitMethod)
parameterChoices <- c('KTrans','ve', 'kep')

shinyApp(
  ui = fluidPage(
    titlePanel("Parameter Estimates - Reference Region Model"),
    sidebarLayout(
      sidebarPanel(
        uiOutput("selectModel"),
        selectInput("plotVarA", label = "Parameter of Interest",
                    choices=parameterChoices),
        selectInput("TResA", label = "Temporal Resolution",
                    choices=TResChoices)
      ),
      mainPanel(
        plotOutput("mainPlot")
      )
    )
  ),
  
  server = function(input, output) {
    
    output$selectModel <- renderUI({
	    selectInput("selectedModels", "Select Model/Method(s):",
		  modelChoices,
		  selected=modelChoices[1],multiple=TRUE)
	  })

    
    localData <- reactive({
      subData <- subset(csvData, FitMethod %in% input$selectedModels)
      subData <- subset(subData, TemporalRes == input$TResA)
      return(subData)
    })
    
    output$mainPlot <- renderPlot({
      if (input$plotVarA == 'KTrans') {
        plotData <- data.frame(x = localData()$CNR,
                                y = localData()$errKt,
                                std = localData()$stdErrKt,
                                fGroup = localData()$FitMethod)
        curX <- 'CNR'
        curY <- 'Percent Error in KTrans'
        curTitle <- paste('Percent error in KTrans when Temporal Res =', input$TResA)
        
      } else if (input$plotVarA == 've') {
        plotData <- data.frame(x = localData()$CNR,
                                y = localData()$errVe,
                                #To show ErrorBars for Ve, change next line to: std = localData()$stdErrVe,
                                std = 0,
                                fGroup = localData()$FitMethod)
        curX <- 'CNR'
        curY <- 'Percent Error in Ve'
        curTitle <- paste('Percent error in ve when Temporal Res =', input$TResA)
      } else if (input$plotVarA == 'kep') {
        plotData <- data.frame(x = localData()$CNR,
                                y = localData()$errKep,
                                std = localData()$stdErrKep,
                                fGroup = localData()$FitMethod)
        curX <- 'CNR'
        curY <- 'Percent Error in Kep'
        curTitle <- paste('Percent error in kep when Temporal Res =', input$TResA)
      }
      limits <- aes(ymax = y + std, ymin=y - std)
      p <- ggplot(plotData, aes(y=y, x=x, colour=fGroup)) + 
        geom_line(size=1) + 
        geom_errorbar(limits, width=3, size=1, position=position_dodge(width = 0.4)) +
        xlab(curX) + ylab(curY) + ggtitle(curTitle)
      return(p)
    })
    
  },
  
  options = list(height = 600)
)
```
